Config = {}

Config.Debug = false

Config.VerifySociety = {
    'vallaw',
    'rholaw',
    'blklaw',
    'strlaw',
    'stdenlaw',
    'medic',
    'valsaloontender',
    'blasaloontender',
    'rhosaloontender',
    'stdenissaloontender1',
    'stdenissaloontender2',
    'vansaloontender',
    'armsaloontender',
    'tumsaloontender',
    'moonsaloontender1',
    'moonsaloontender2',
    'moonsaloontender3',
    'moonsaloontender4',
    'moonsaloontender5',
    'stdeniswholesale',
    'blkwholesale',
    'railroad',
    'govenor1',
    'govenor2',
    'govenor3',
    'govenor4',
    'govenor5',
    'valweaponsmith',
    'rhoweaponsmith',
    'stdweaponsmith',
    'tumweaponsmith',
    'annweaponsmith',
}
